### ISSUE TITLE
Configuration fields

### ISSUE THREAD

**Issue by cjdduarte** [AlexRiina/anki_cousins#1]
What values ​​do I put here?

![image](https://user-images.githubusercontent.com/42243532/81281071-c28b6780-902f-11ea-9d84-ac91a8ab3ebc.png)

**Comment by noobj2** [comment]
you should put the field name that you want to detect there,
for example,
on note "Basic" | match field "Front"
to note "Basic" | match field "Front"
will check "Front" field from "Basic" note type for similarities

**Comment by cjdduarte** [comment]
Tanks
