### ISSUE TITLE
Unable to set a config

### ISSUE THREAD

**Issue by michaelcward1996** [AlexRiina/anki_cousins#13]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-01-01 20:46:28

Caught exception:
Traceback (most recent call last):
  File "aqt\addons.py", line 896, in onConfig
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\1072815885\interface.py", line 81, in show_settings_dialog
    SettingsManager(col).save(
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\1072815885\settings.py", line 80, in save
    set_config = self.col.set_config()
TypeError: set_config() missing 2 required positional arguments: 'key' and 'val'

These are the extensions I have right now. 
![image](https://user-images.githubusercontent.com/33991266/103451394-92589f00-4c78-11eb-932e-7bf7ae0170c5.png)

**Comment by michaelcward1996** [comment]
This might just be something wrong with my system. Anki's regular "bury related cards" isn't working for me either. Also happy new year, :) 
![image](https://user-images.githubusercontent.com/33991266/103451454-1743b880-4c79-11eb-92d4-29c7b8725534.png)

**Comment by AlexRiina** [comment]
Thanks for reporting that. I must have missed that when I thought I was QAing it. The fix is pretty simple and I should be able to upload a new release before long.

**Comment by AlexRiina** [comment]
Just pushed a new release with this fix onto ankiweb
