### ISSUE TITLE
seems can't bury card，i don't know where had a problem

### ISSUE THREAD

**Issue by freemedom** [AlexRiina/anki_cousins#15]
![image](https://user-images.githubusercontent.com/57294686/109149078-0d829100-77a2-11eb-9cf6-b775236ba4b0.png)
the concrete field content in the browser
![image](https://user-images.githubusercontent.com/57294686/109149257-47ec2e00-77a2-11eb-8161-f3eb6765f0f4.png)

**Comment by freemedom** [comment]
"testtest11" card isn't buried

**Comment by freemedom** [comment]
In addition, I actually prefer that this addon can postpone the due date for a few days of the related card, in stead of just burying related card.(￣▽￣)"

**Comment by AlexRiina** [comment]
Hi @freemedom, thanks for submitting this bug. I think I've reproduced the issue but want to make sure I'm looking at the same thing.

Do you have "Bury related new cards until the next day" and "Bury related review cards until the next day" checked (see image)
![Screenshot from 2021-03-13 15-36-26](https://user-images.githubusercontent.com/4087850/111043711-fc788780-8411-11eb-8cd7-582149435b61.png)
?

When I have them checked, the cards are buried correctly, but if I uncheck them, then it looks like Anki is unburying them and I get some silly behavior like seeing negative number of review cards remaining. What version of Anki are you seeing this with? I'm seeing my issue with 2.1.42 but it may have appeared earlier.

**Comment by freemedom** [comment]
@AlexRiina 
good,after I have them checked, the cards are buried correctly
