### ISSUE TITLE
Suggestion: Fuzzy String Matching 

### ISSUE THREAD

**Issue by cjdduarte** [AlexRiina/anki_cousins#2]
Would the suggestion for an approximate search algorithm be open?
I loved the idea of ​​your addon.
Congratulations

**Comment by AlexRiina** [comment]
Thanks! 

The "by similarity" setting is supposed to do fuzzy matching based on python's [difflib](https://docs.python.org/3/library/difflib.html)

> The idea is to find the longest contiguous matching subsequence [...] The same idea is then applied recursively to the pieces of the sequences to the left and to the right of the matching subsequence. This does not yield minimal edit sequences, but does tend to yield matches that “look right” to people.

```
difflib.SequenceMatcher(None, '123123aaaaaa', '9aaaaaa87987').ratio()
# 0.5

difflib.SequenceMatcher(None, 'c', '1aaaaaa87987').ratio()
# 0.5833333333333334
```

I think in the second example, it first finds aaaaaa as 6 matches and then finds the first 1 as a 7th match so then the ratio is `(6 + 1) * 2 / (len("123123aaaaaa") + len("1aaaaaa87987")) = 0.588`. 

Definitely not clearly documented what the setting does or how it works currently.
