### ISSUE TITLE
Add-on has no configuration !?

### ISSUE THREAD

**Issue by gravidarum** [AlexRiina/anki_cousins#27]
Version ⁨2.1.43 (0fbae6bc)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2

at first the add on didn't work for some cards(imageOcclusioncard Specifically i use it for )
i went into setting and i can see the config and i can click it this time ,so i click it to see any problem in there but everything was fine,so i was confused!
and then disabled the addon [Bury Cousins (related cards that aren't siblings)]
and i tried this add on : [[Bury related notes](https://ankiweb.net/shared/info/413416269)]
i couldn't make this new add on work neither, or i didn't know exactly how it work!  so i decided to disable it and back to (Bury Cousins) addon,
hereafter i toggle enable it, I couldn't press the config button, and even if i double click on it show this message saying [Add-on has no configuration]: 
![image](https://user-images.githubusercontent.com/86447395/123345988-8e3a7980-d557-11eb-97a9-2a8d9ee02607.png)

tried to delete and reinstall the addon from start but nothing works, still no config button !!?

**Comment by gravidarum** [comment]
huh i just restarted the device and it showed up!
![image](https://user-images.githubusercontent.com/86447395/123350043-7ca6a100-d55a-11eb-8962-2cf3bbd0be3e.png)

but still, some cards won't be buried, it doesn't work on all cards !!

**Comment by AlexRiina** [comment]
Thanks for reporting, I'll add a manifest and hopefully fix some of the other open tickets and release a new version soon

**Comment by AlexRiina** [comment]
> huh i just restarted the device and it showed up!
> ![image](https://user-images.githubusercontent.com/86447395/123350043-7ca6a100-d55a-11eb-8962-2cf3bbd0be3e.png)
> 
> but still, some cards won't be buried, it doesn't work on all cards !!

I'm not familiar with the Image Occlusion plugin, can you add some example values for the image field. Assuming they're HTML, can you copy the raw html from the `ctrl+shift+x` screen while editing the Image field?

**Comment by gravidarum** [comment]
the add-on link : 
[Image Occlusion Enhanced for Anki 2.1 (alpha)](https://ankiweb.net/shared/info/1374772155)
and those are the fields : 
![image](https://user-images.githubusercontent.com/86447395/123351345-3141c200-d55d-11eb-8aac-307e427472c8.png)

i didn't get what u mean by HTML "ctrl+shft+x" I did this shortcut while in the editing field of the "Image" field and nothing happensed!

**Comment by AlexRiina** [comment]
Here's a quick video of accessing the menu for the same tool. I'm wondering if the image urls are totally different between cards or if there's any way to tell that they're from the same original image. Are any of those other fields useful for this?

https://user-images.githubusercontent.com/4087850/123352787-13109d80-d52e-11eb-8a6a-17ed13844844.mp4

**Comment by gravidarum** [comment]
i did that and it was the same HTML text, 
apparently, the issue is related to the Ankidroid,
so what i normally do is , that i  add my cards on the PC, and then study them on the Ankidroid,

i just tested it , so i added cards on PC and first, i studied(learning) those "New" cards on PC, here the add on work perfectly.
then i added other cards on PC and study those "New" cards on ankidroid used (again/good/easy/burry) and then sync those to test them on PC, Here in the PC the add-on didn't work on those cards!! (the one that has been learned on ankidroid and synced on pc).!

**Comment by AlexRiina** [comment]
This should be fixed now with #28 as I've added a manifest.json file.
