### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by arisaeedi** [AlexRiina/anki_cousins#5]
I love your add-on but have a request if you have the time!! 

I'm in medical school and use a lot of premade decks that have overlapping concepts or straight up the same concepts re-worded differently or in a different card format. This especially happens when using multiple decks from different people. For example:

1."Cloze vs basic card types"

Cloze:

{{c1:Kallmann syndrome}} is a cause of delayed puberty that also causes anosmia.

Basic:

Front: What cause of delayed puberty also causes anosmia? 

Back: Kallmann syndrome

2."Cloze vs Cloze"

{{c1:Kallmann syndrome}} is a cause of delayed puberty that also causes anosmia. 

{{c1:Kallmann syndrome}} causes delayed puberty and anosmia.

Now imagine this but a lot lot more of it. The repetitions add up and take up a lot of time. Could we have a feature that has the same functionality as your current one in finding similar cards, but instead of burying them, tag them or allow a browser view of all similar cards sorted based on (%) similarity. 

End goal: Do less of the same card lol. It would be nice if the add-on confirmed deletions and what-not. I know there is a lot of people on r/medschoolanki that would love this ability.

**Comment by AlexRiina** [comment]
Thanks, @arisaeedi! I'm happy to hear you find it useful. 

My initial impression was that the current implementation would be too slow to support looking at large pre-made decks but that the functionality would still be great to have. My own decks have some repeated concepts and auto-generated cards from previous experiments and I'd love to clean them up.

So anyway, I took a stab at it and threw it into https://github.com/AlexRiina/anki_cousins/pull/6
![duplicates](https://user-images.githubusercontent.com/4087850/87214137-28c68c00-c2f8-11ea-872a-139f46f3146b.gif) which you can either install locally if following along with the readme or install from 
[plugin.zip](https://github.com/AlexRiina/anki_cousins/files/4906137/plugin.zip) (probably good to make a backup of your deck just in case).

With that, you'd be able to find duplicate notes using your rules, mark them with a tag like duplicate-deck1-deck2 and then suspend cards from either deck that match those tags. I'd bet in some cases, there are duplicate cards but not all cards on two identified notes are duplicates, so someone would have to pick the ones to suspend carefully, but hopefully this at least makes a clear checklist.

**Comment by arisaeedi** [comment]
That was so fast! It works perfectly other than the fact that you called it with not running ultra smooth on huge decks. Regardless, this was exactly what I was looking for. Thank you so much. If you incorporate it into a final build (sorry dunno the lingo here super well), would you be okay if I shared your add-on page with the subreddit?

**Comment by AlexRiina** [comment]
Thanks, it was definitely pretty slow on my main anki profile and that was sometimes causing my OS to ask if I wanted to kill the process. I've reimplemented the similarity check and replaced the very inefficient way that I was building the list of duplicated notes.

For me, the version I uploaded before took about a minute to calculate the duplicates on my full deck and now takes about 7 seconds. If you have time I'd be curious to see if this version is faster for you as well. I just dropped another plugin file into https://github.com/AlexRiina/anki_cousins/pull/6#issuecomment-657165112

**Comment by AlexRiina** [comment]
I've just released an update to the plugin that includes the code changes in #6. If the "detect duplicates" functionality still isn't working well for you in the updated version, let me know what kind of rules you have configured and I'll see if I can find a better way to do that calculation. I've updated just the similarity rule, but some of the others could use some love.

Please feel free to share with anyone you think would fine it useful
