### ISSUE TITLE
No 'config' available in Anki 2.1.35

### ISSUE THREAD

**Issue by Littlegator** [AlexRiina/anki_cousins#9]
This may not be a new problem, as I have never used the addon before. The "Config" button for this addon is grayed out in the Add-Ons menu.

**Comment by AlexRiina** [comment]
Thanks for the report, the button should definitely be clickable and will lead to all of the configuration options normally. I've just updated from 2.1.33 to 2.1.35 to reproduce the error but the button is clickable for me.

![Screenshot from 2020-10-06 23-58-57](https://user-images.githubusercontent.com/4087850/95286210-b733a680-0830-11eb-85d8-eb4091a578ee.png)

From what I can tell, Anki enables the button if the plugin has a default config.json file (which this doesn't) or if it defines a config action ([which this plugin does](https://github.com/AlexRiina/anki_cousins/blob/master/src/interface.py#L211)). So my suspicion is that for some reason the config action isn't registering for you.

Do you see any errors on starting Anki? Can you add some details about any other plugins you have installed and your operating system just to help me reproduce the issue. If you're able, can you also try disabling other plugins to see if there's a specific one that conflicts?

One more debugging step: can you open the [debug console](https://apps.ankiweb.net/docs/manual20.html#debug-console) `ctrl+shift+; on windows / linux and `command+shift+;` on mac and run

```python
print(mw.addonManager._configButtonActions)
```

(have to hit `ctrl-enter` to run the command) and paste the output here. That'll show me a list of all of the plugins you've installed that have registered config actions. For me, for example, this shows 
![Screenshot from 2020-10-07 00-31-34](https://user-images.githubusercontent.com/4087850/95287675-805f8f80-0834-11eb-8f48-9affe6ca0904.png)

If you're a developer and interested in tracing down the issue by writing a little python, I can send over some instructions on building a local copy of this plugin and where to inject some print statements.

**Comment by Littlegator** [comment]
Genuinely don't know what happened, as I troubleshot this quite a bit last night to no avail (reinstalling add-on, reinstalling anki, disabling all other addons, etc.). Synced my deck overnight and when I woke up this morning, the button was available. So I guess issue resolved?

Btw, I don't really know if this warrants a separate issue, but can you provide any more instruction on "These rules can are also used in identifying duplicate cards in the card browser" as stated in the README? I'd love to be able to sort through the cousins and pick out which one I want to keep. I inherited a very good deck for my school, but for some reason some cards have 5+ fuzzy duplicates and I suspect I'm doing 100+ duplicates a day.

**Comment by AlexRiina** [comment]
Weird / glad to hear. I haven't made any recent changes so it must have just resolved on its own.

Re the duplicate finder:

I can definitely flesh that section out a bit. The gist is that in the card browser if you click Notes->Find Duplicates, the duplicate search will also use the custom rules you've defined and present the output in a slightly different format but mostly behaves the same. 

For me, if I select Search In: Text with no optional filters, I get output like

> 2 notes: [cloze_contained_by] Mas yo temía de ver una grande {{c1::restinga::shoal}} de piedras que cerca toda aquella isla alrededor, y entre medias queda hondo el puerto para cuantas naos hay en toda la Cristiandad, y la entrada de ello muy angosta.

and when I click the "2 notes" it pulls up some automatic cloze cards that cover the same sentences

> Mas yo temía de ver una grande {{c1::restinga::shoal}} de piedras que cerca toda aquella isla alrededor, y entre medias queda hondo el puerto para cuantas naos hay en toda la Cristiandad, y la entrada de ello muy angosta.

> Mas yo temía de ver una grande restinga de piedras que cerca toda aquella isla alrededor, y {{c1::entre medias::in between}} queda hondo el puerto para cuantas naos hay en toda la Cristiandad, y la entrada de ello muy angosta.

That functionality's a bit experimental and the performance on a large deck may be bad for some kinds of matches, but hopefully you find it useful.

**Comment by Littlegator** [comment]
Interesting! I got it to work. Thank you! Everything is in order.
